### ISSUE TITLE
Is there any plan to add feature for video resize

### ISSUE THREAD

**Issue by priyabratap** [jonataslaw/VideoCompress#111]
Really a nice package. 

It would be better if we add functionality to do resize of video dimensions. 

Is there any plan!?

**Comment by yanivshaked** [comment]
You are welcome to try my PR and comment:
[Link](https://github.com/jonataslaw/VideoCompress/pull/119)

**Comment by yanivshaked** [comment]
You can try this feature on the latest master:
```
video_compress:
  git:
    url: https://github.com/jonataslaw/VideoCompress
    ref: "583e700"
```
