### ISSUE TITLE
how to solve : Compress.getThumbnail error: type 'Future<String?>' is not a subtype of type 'FutureOr<String>' in type cast 

### ISSUE THREAD

**Issue by lxl518000** [jonataslaw/VideoCompress#114]
Compress.getThumbnail error: type 'Future<String?>' is not a subtype of type 'FutureOr<String>' in type cast

i try to use 
 video_compress:
    git:
      url: https://github.com/jonataslaw/VideoCompress.git

but it doesn't work,and other errors appeared

**Comment by yanivshaked** [comment]
Use the latest version for a fix, until @jonataslaw provides a new release:
```
video_compress:
  git:
    url: https://github.com/jonataslaw/VideoCompress
    ref: "583e700"
```
