### ISSUE TITLE
Unhandled Exception: type 'Future<String?>' is not a subtype of type 'FutureOr<String>' in type cast

### ISSUE THREAD

**Issue by ccamba** [jonataslaw/VideoCompress#120]
Hi, a found a bug here:

`  Future<MediaInfo> getMediaInfo(String path) async {
    **final jsonStr = await (_invoke<String>('getMediaInfo', {'path': path}) as FutureOr<String>);**
    final jsonMap = json.decode(jsonStr);
    return MediaInfo.fromJson(jsonMap);
  }`

**Comment by rodrigoschaefer** [comment]
Same error here

**Comment by yanivshaked** [comment]
Use the latest version for a fix, until @jonataslaw provides a new release:
```
  video_compress:
    git:
      url: https://github.com/yanivshaked/VideoCompress
      ref: "ef123af"
```
