### ISSUE TITLE
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.40 and higher.

### ISSUE THREAD

**Issue by maddhy** [jonataslaw/VideoCompress#142]
* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.40 and higher.
The following dependencies do not satisfy the required version:
project ':video_compress' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.31

**Comment by EireHauler** [comment]
Same issue is here.

**Comment by denes16** [comment]
same

**Comment by josedavidrp** [comment]
You can fix it going to the build.gradle  of the plugin and changing ext.kotlin_version to '1.3.40'. I dont know if everything will work, but I could compress a video and make a successful build with this.
To find this file you have to go to your flutter folder>.pub-cache>hosted>pub.dartlang.org>video_compress-3.1.0>android>build.gradle. 

I dont know if that file is overwritten usually or something, but if it does working just go there and change it again

**Comment by Pavlouha** [comment]
Yep, yep.
The real problem is that the pub.dev contains a previous version of this library (3.1.0). How to update:

- In your pubspec.yaml

```
  #video_compress: ^3.1.0
  video_compress:
    git:
      url: https://github.com/jonataslaw/VideoCompress.git
      ref: master
```
